CXX=clang++
OPT=opt

TARGET=bots-sort.out
PROG=bots-sort.out
OBJS=bots_main.o bots_common.o sort.o 
INTERMEDIATES=bots_main.bc bots_common.bc sort.bc
CXXFLAGS := -fopenmp -g -O1
LDFLAGS = -fopenmp -g

PASS_COMPILE_FLAGS =  -fopenmp -DOMPR -I./ -I$(LLVM_HOME)/include -I$(OMPP_ROOT)/src/omprace/ -I$(OMPP_ROOT)/src/include -g -c
OPT_FLAGS = -load $(HOME)/llvm-src-60/llvm/build/lib/DataAnnotation.so -DataAnnotation
omprace_compile_flags = -I./ -I$(LLVM_HOME)/include -I$(OMPP_ROOT)/src/omprace/ -I$(OMPP_ROOT)/src/include -g $(OMPP_ROOT)/src/omprace/libomprace.a

all : $(PROG)

$(PROG) : $(OBJS)
	$(CXX) -lm -fopenmp  $(OBJS) $(omprace_compile_flags) -o $(PROG) 

 
%.o : %.c 
	$(CXX) $(CXXFLAGS) $(PASS_COMPILE_FLAGS) $<


clean:
	rm -f *.o $(TARGET) *~ *.out *.txt *.ll *.bc
