CXX=clang++
OPT=opt

TARGET=bots-sort.out
PROG=bots-sort.out
OBJS=bots_main.o bots_common.o sort.o 
INTERMEDIATES=bots_main.bc bots_common.bc sort.bc
CXXFLAGS := -fopenmp -g -O3 -fsanitize=thread
LDFLAGS = -fopenmp -g -O3 -fsanitize=thread

PASS_COMPILE_FLAGS =  -fopenmp -g -c
omprace_compile_flags = -g

all : $(PROG)

$(PROG) : $(OBJS)
	$(CXX) -lm $(LDFLAGS) $(OBJS) $(omprace_compile_flags) -o $(PROG) 

 
%.o : %.c 
	$(CXX) $(CXXFLAGS) $(PASS_COMPILE_FLAGS) $<


clean:
	rm -f *.o $(TARGET) *~ *.out *.txt *.ll *.bc
