CXX=clang++
OPT=opt

TARGET=bots-alignment-for.out
PROG=bots-alignment-for.out
OBJS=bots_main.o bots_common.o sequence.o alignment.o 
INTERMEDIATES=bots_main.bc bots_common.bc sequence.bc alignment.bc
CXXFLAGS := -fopenmp -g -O3
LDFLAGS = -fopenmp -g -O3

PASS_COMPILE_FLAGS =  -I./ -c
omprace_compile_flags = -I./

all : $(PROG)

$(PROG) : $(OBJS)
	$(CXX) $(LDFLAGS) $(OBJS) $(omprace_compile_flags) -o $(PROG) 
 
%.o : %.c 
	$(CXX) $(CXXFLAGS) $(PASS_COMPILE_FLAGS) $<

clean:
	rm -f *.o $(TARGET) *~ *.out *.txt *.ll *.bc
