#!/usr/bin/python

bnchmrk="MST"
benchmark="Minimum Spanning Tree"
checkProgram="../common/MSTCheck"
dataDir = "../graphData/data"

tests = [
    [1, "randLocalGraph_WE_5_40000000", "", ""],
    [1, "rMatGraph_WE_5_40000000", "", ""],
    [1, "2Dgrid_WE_64400000", "", ""]
    ]

import runTests
runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, tests)

