#!/usr/bin/python

bnchmrk="dict"
benchmark="Dictionary"
checkProgram="../common/dictCheck"
dataDir = "../sequenceData/data"

tests = [
    [1, "randomSeq_100M_int", "", ""],
    [1, "randomSeq_100M_100K_int", "", ""],
    [1, "exptSeq_100M_int", "", ""],
    [3, "trigramSeq_100M", "", ""],
    [3, "trigramSeq_100M_pair_int", "", ""]
    ]


import runTests
runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, tests)
