CXX=clang++
OPT= opt

TARGET=bots-floorplan.out
PROG=bots-floorplan.out
OBJS=bots_main.o bots_common.o floorplan.o 
INTRMEDIATES=bots_main.bc bots_common.bc floorplan.bc 
CXXFLAGS := -fopenmp -DMANUAL_CUTOFF -g -O3
LDFLAGS = -fopenmp -g

PASS_COMPILE_FLAGS =  -fopenmp -DOMPR -I./ -I$(LLVM_HOME)/include -I$(OMPP_ROOT)/src/omprace/ -I$(OMPP_ROOT)/src/include -g -c
OPT_FLAGS = -load $(HOME)/llvm-src-60/llvm/build/lib/DataAnnotation.so -DataAnnotation
omprace_compile_flags = -I./ -I$(LLVM_HOME)/include -I$(OMPP_ROOT)/src/omprace/ -I$(OMPP_ROOT)/src/include -g $(OMPP_ROOT)/src/omprace/libomprace.a

all : $(PROG)
$(PROG) : $(OBJS)
	$(CXX) -lm $(LDFLAGS) $(OBJS) $(omprace_compile_flags) -o $(PROG) 

 
%.o : %.c 
	$(CXX) $(CXXFLAGS) $(PASS_COMPILE_FLAGS) $<


clean:
	rm -f *.o $(TARGET) *~ *.out *.txt  *.ll *.bc
