CXX=clang++
OPT= opt

TARGET=bots-floorplan.out
PROG=bots-floorplan.out
OBJS=bots_main.o bots_common.o floorplan.o 
INTRMEDIATES=bots_main.bc bots_common.bc floorplan.bc 
CXXFLAGS := -fopenmp -DMANUAL_CUTOFF -g -O3 -fsanitize=thread 
LDFLAGS = -fopenmp -g -O3 -fsanitize=thread 

PASS_COMPILE_FLAGS =  -fopenmp -g -c
omprace_compile_flags = -I./ -g

all : $(PROG)
$(PROG) : $(OBJS)
	$(CXX) -lm $(LDFLAGS) $(OBJS) $(omprace_compile_flags) -o $(PROG) 

 
%.o : %.c 
	$(CXX) $(CXXFLAGS) $(PASS_COMPILE_FLAGS) $<


clean:
	rm -f *.o $(TARGET) *~ *.out *.txt  *.ll *.bc
