#!/usr/bin/python

bnchmrk="BFS"
benchmark="Breadth First Search"
checkProgram="../common/BFSCheck"
dataDir = "../graphData/data"

tests = [
    [1, "randLocalGraph_J_5_40000000", "", ""],
    [1, "rMatGraph_J_5_40000000", "", ""],
    [1, "3Dgrid_J_64400000", "", ""]
    ]    

import runTests
runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, tests)

