CXX=clang++
OPT=opt

TARGET=bots-sparselu-single.out
PROG=bots-sparselu-single.out
OBJS=bots_main.o bots_common.o sparselu.o 
INTERMEDIATES=bots_main.bc bots_common.bc sparselu.bc
CXXFLAGS := -fopenmp -g -O3 -fsanitize=thread 
LDFLAGS = -fopenmp -g -O3 -lm -fsanitize=thread 

PASS_COMPILE_FLAGS =  -fopenmp -g -c
omprace_compile_flags = -I./ -g

all : $(PROG)

$(PROG) : $(OBJS)
	$(CXX) $(LDFLAGS) $(OBJS) $(omprace_compile_flags) -o $(PROG)  
 
%.o : %.c 
	$(CXX) $(CXXFLAGS) $(PASS_COMPILE_FLAGS) $<

clean:
	rm -f *.o $(TARGET) *~ *.out *.txt *.ll *.bc
