CXX=clang++
OPT=opt

TARGET=bots-nqueens.out
PROG=bots-nqueens.out
OBJS=bots_main.o bots_common.o nqueens.o 
INTERMEDIATES=bots_main.bc bots_common.bc nqueens.bc
CXXFLAGS := -fopenmp -DMANUAL_CUTOFF -g -O3
LDFLAGS = -fopenmp -g -O3

PASS_COMPILE_FLAGS =  -fopenmp -I./ -g -c
omprace_compile_flags = -I./ -g

all : $(PROG)

$(PROG) : $(OBJS)
	$(CXX) -lm $(LDFLAGS) $(OBJS) $(omprace_compile_flags) -o $(PROG) 
 
%.o : %.c 
	$(CXX) $(CXXFLAGS) $(PASS_COMPILE_FLAGS) $<


clean:
	rm -f *.o $(TARGET) *~ *.out *.txt *.ll *.bc
