#!/usr/bin/python

bnchmrk="ST"
benchmark="Spanning Tree"
checkProgram="../common/STCheck"
dataDir = "../graphData/data"

tests = [
    [1, "randLocalGraph_E_5_40000000", "", ""],
    [1, "rMatGraph_E_5_40000000", "", ""],
    [1, "3Dgrid_E_64400000", "", ""],
    ]

import runTests
runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, tests)

